### ISSUE TITLE
how to open `.kfb` files by python

### ISSUE THREAD

**Issue by caibojun** [liyu10000/tct#1]
Hi,
I wonder how you process `.kfb` files in python. I noticed that you open them by a third library name `tslide`, so how can I get the code of that, thx!

**Comment by liyu10000** [comment]
> Hi,
> I wonder how you process `.kfb` files in python. I noticed that you open them by a third library name `tslide`, so how can I get the code of that, thx!

Hi,

We developed a openslide-like tool to process .kfb files. It is in the archived/kfb_reader folder. Pay special attention to the work of tslide and tslide2. It is a python wrapper of .so libs (not included in this repo).

**Comment by caibojun** [comment]
> > Hi,
> > I wonder how you process `.kfb` files in python. I noticed that you open them by a third library name `tslide`, so how can I get the code of that, thx!
> 
> Hi,
> 
> We developed a openslide-like tool to process .kfb files. It is in the archived/kfb_reader folder. Pay special attention to the work of tslide and tslide2. It is a python wrapper of .so libs (not included in this repo).

Obviously I'm too careless to notice that, your advise helped a lot, I couldn't appreciate more about that.
