### ISSUE TITLE
windows系统kfb文件的解析问题

### ISSUE THREAD

**Issue by houchangchang** [liyu10000/tct#3]
请问这个项目支持windows系统解析kfb文件吗，我把代码下载下来之后运行**train_c1/roi_extract/Aslide/kfb/kfb_slide.py**文件 会报错**FileNotFoundError: Could not find module 'libkfbslide.so' (or one of its dependencies). Try using the full path with constructor syntax.**

**Comment by liyu10000** [comment]
你好，so文件是用于Linux系统的，要在windows上运行需要dll文件。你可以看一下train_c1/roi_extract/Aslide/kfb/kfb_lowlevel.py 第14行的代码，可能需要你自己在网上找一下dll了。kfb是江丰公司专用的文件格式，官网上并没有，但是别人的GitHub里会有存留，我当时也是这样找到的。找不到的话可以来问我

**Comment by liyu10000** [comment]
我刚又找到了另一种Windows上打开kfb的方法，要复杂一些。代码在ocr/ocr_python/LabelReader.py第32行有示例，这个dll这里是有的
